package audit

import (
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"testing"
	"time"
)

// Each fixture is a cut-down copy of what the tool actually writes, keeping
// the shapes that decide the parse — the peer-dependency suffix pnpm appends,
// the workspace entry Berry records and v1 does not, the `files = [` array
// Poetry puts between a package and its dependency table.

func chains(t *testing.T, g graph, eco, name string) []string {
	t.Helper()
	var out []string
	for _, c := range g.via(ref(eco, name), maxWhyChains, maxWhyDepth) {
		names := make([]string, 0, len(c))
		for _, r := range c {
			names = append(names, refName(r))
		}
		out = append(out, strings.Join(names, ">"))
	}
	sort.Strings(out)
	return out
}

func wantChains(t *testing.T, g graph, eco, name string, want ...string) {
	t.Helper()
	sort.Strings(want)
	if got := chains(t, g, eco, name); !reflect.DeepEqual(got, want) {
		t.Errorf("chains to %s: got %v, want %v", name, got, want)
	}
}

// wantRelation asks about a package at a version, because that is what a
// component is: a name with no version is not a row any report ever holds, and
// the formats that pin a direct dependency pin it *at* a version.
func wantRelation(t *testing.T, g graph, eco, name, version, want string) {
	t.Helper()
	c := component{ecosystem: eco, name: name, version: version}
	if got := g.relation(c, nil); got != want {
		t.Errorf("%s %s is %q, want %q", name, version, describe(got), describe(want))
	}
}

func describe(rel string) string {
	if rel == relUnstated {
		return "not stated"
	}
	return rel
}

func TestGoModMarksIndirect(t *testing.T) {
	g := goModGraph(`module example.com/x

go 1.24

require (
	github.com/spf13/cobra v1.8.0
	golang.org/x/sys v0.20.0 // indirect
)

require github.com/stretchr/testify v1.9.0 // indirect
`)
	wantRelation(t, g, "Go", "github.com/spf13/cobra", "v1.8.0", relDirect)
	wantRelation(t, g, "Go", "golang.org/x/sys", "v0.20.0", relIndirect)
	wantRelation(t, g, "Go", "github.com/stretchr/testify", "v1.9.0", relIndirect)
	// go.mod records no edges at all, and inventing one would be inventing
	// the module graph. `go mod why` is what has it.
	if len(g.requires) != 0 {
		t.Errorf("go.mod produced edges it cannot know: %v", g.requires)
	}
}

func TestNpmLockDirectAndTransitive(t *testing.T) {
	g := npmLockGraph([]byte(`{
	  "name": "demo",
	  "lockfileVersion": 3,
	  "packages": {
	    "": {
	      "name": "demo",
	      "dependencies": { "express": "^4.17.1" },
	      "devDependencies": { "jest": "^26.0.0" }
	    },
	    "packages/api": { "dependencies": { "pg": "^8.0.0" } },
	    "node_modules/express": { "version": "4.17.1", "dependencies": { "qs": "6.7.0" } },
	    "node_modules/jest": { "version": "26.0.0", "dependencies": { "minimist": "1.2.0" } },
	    "node_modules/qs": { "version": "6.7.0" },
	    "node_modules/jest/node_modules/minimist": { "version": "1.2.0" },
	    "node_modules/pg": { "version": "8.0.0" }
	  }
	}`))
	wantRelation(t, g, "npm", "express", "4.17.1", relDirect)
	// A workspace's own package.json entry is as direct as the root's.
	wantRelation(t, g, "npm", "pg", "8.0.0", relDirect)
	wantRelation(t, g, "npm", "qs", "6.7.0", relIndirect)
	wantChains(t, g, "npm", "qs", "express>qs")
	wantChains(t, g, "npm", "minimist", "jest>minimist")
}

func TestPnpmImportersAndSnapshots(t *testing.T) {
	g := pnpmGraph(`lockfileVersion: '9.0'

settings:
  autoInstallPeers: true

importers:

  .:
    dependencies:
      express:
        specifier: ^4.17.1
        version: 4.17.1
    devDependencies:
      jest:
        specifier: ^26.0.0
        version: 26.0.0

packages:

  express@4.17.1:
    resolution: {integrity: sha512-aaa}

  qs@6.7.0:
    resolution: {integrity: sha512-bbb}

snapshots:

  express@4.17.1:
    dependencies:
      qs: 6.7.0
      '@types/node': 20.11.0

  qs@6.7.0: {}
`)
	wantRelation(t, g, "npm", "express", "4.17.1", relDirect)
	wantRelation(t, g, "npm", "jest", "26.0.0", relDirect)
	wantRelation(t, g, "npm", "qs", "6.7.0", relIndirect)
	wantChains(t, g, "npm", "qs", "express>qs")
	// A scoped name is one key, not a scope and a package.
	wantChains(t, g, "npm", "@types/node", "express>@types/node")
}

func TestYarnBothDialects(t *testing.T) {
	v1 := yarnGraph(`# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


express@^4.17.1:
  version "4.17.1"
  resolved "https://registry.yarnpkg.com/express/-/express-4.17.1.tgz#abc"
  dependencies:
    qs "6.7.0"
    "@babel/core" "^7.0.0"

qs@6.7.0:
  version "6.7.0"
`)
	wantChains(t, v1, "npm", "qs", "express>qs")
	wantChains(t, v1, "npm", "@babel/core", "express>@babel/core")
	// v1 records no workspace entries, so nothing in it says which
	// dependencies the project asked for. That has to read as silence.
	wantRelation(t, v1, "npm", "express", "4.17.1", relUnstated)

	berry := yarnGraph(`# This file is generated by running "yarn install"

__metadata:
  version: 8

"demo@workspace:.":
  version: 0.0.0-use.local
  resolution: "demo@workspace:."
  dependencies:
    express: "npm:^4.17.1"
  languageName: unknown

"express@npm:4.17.1":
  version: 4.17.1
  resolution: "express@npm:4.17.1"
  dependencies:
    qs: "npm:6.7.0"

"qs@npm:6.7.0":
  version: 6.7.0
`)
	wantRelation(t, berry, "npm", "express", "4.17.1", relDirect)
	wantRelation(t, berry, "npm", "qs", "6.7.0", relIndirect)
	wantChains(t, berry, "npm", "qs", "express>qs")
}

func TestBunLockWorkspacesAndEntries(t *testing.T) {
	g := bunGraph([]byte(`{
	  // bun writes JSONC
	  "lockfileVersion": 1,
	  "workspaces": {
	    "": { "name": "demo", "dependencies": { "express": "^4.17.1" } },
	  },
	  "packages": {
	    "express": ["express@4.17.1", "", { "dependencies": { "qs": "6.7.0" } }, "sha512-aaa"],
	    "qs": ["qs@6.7.0", "", {}, "sha512-bbb"],
	  },
	}`))
	wantRelation(t, g, "npm", "express", "4.17.1", relDirect)
	wantRelation(t, g, "npm", "qs", "6.7.0", relIndirect)
	wantChains(t, g, "npm", "qs", "express>qs")
}

func TestCargoWorkspaceMemberIsTheProject(t *testing.T) {
	g := tomlGraph(`version = 3

[[package]]
name = "demo"
version = "0.1.0"
dependencies = [
 "serde",
 "tokio 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaa"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_derive"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbb"
`, "crates.io", cargoLock)
	// The entry with no source is the workspace member, so what it requires
	// is what the project asked for.
	wantRelation(t, g, "crates.io", "serde", "1.0.197", relDirect)
	wantRelation(t, g, "crates.io", "tokio", "1.0.0", relDirect)
	wantRelation(t, g, "crates.io", "serde_derive", "1.0.197", relIndirect)
	wantChains(t, g, "crates.io", "serde_derive", "serde>serde_derive")
}

func TestUvVirtualRootIsTheProject(t *testing.T) {
	g := tomlGraph(`version = 1
requires-python = ">=3.11"

[[package]]
name = "demo"
version = "0.1.0"
source = { virtual = "." }
dependencies = [
    { name = "flask" },
]

[[package]]
name = "flask"
version = "3.0.0"
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "click" },
    { name = "jinja2" },
]

[[package]]
name = "click"
version = "8.1.7"
source = { registry = "https://pypi.org/simple" }
`, "PyPI", uvLock)
	wantRelation(t, g, "PyPI", "flask", "3.0.0", relDirect)
	wantRelation(t, g, "PyPI", "click", "8.1.7", relIndirect)
	wantChains(t, g, "PyPI", "click", "flask>click")
}

// Poetry writes the dependency table below a `files = [` array, and spells a
// package one way in the record and another in the table. Both are the kind
// of detail that makes a chain silently stop one step short.
func TestPoetryDependencyTable(t *testing.T) {
	g := tomlGraph(`[[package]]
name = "flask"
version = "3.0.0"
description = "A simple framework"
optional = false
python-versions = ">=3.8"
files = [
    {file = "flask-3.0.0.tar.gz", hash = "sha256:aaa"},
]

[package.dependencies]
click = ">=8.1.3"
Jinja2 = ">=3.1.2"

[[package]]
name = "jinja2"
version = "3.1.2"
optional = false
files = []

[metadata]
lock-version = "2.0"
`, "PyPI", poetryLock)
	wantChains(t, g, "PyPI", "jinja2", "flask>jinja2")
	// poetry.lock says nothing about which dependencies the project asked
	// for — that lives in pyproject.toml, which is not a lockfile.
	wantRelation(t, g, "PyPI", "flask", "3.0.0", relUnstated)
	wantRelation(t, g, "PyPI", "jinja2", "3.1.2", relUnstated)
}

func TestGemfileSpecsAndDependencies(t *testing.T) {
	g := gemfileGraph(`GEM
  remote: https://rubygems.org/
  specs:
    actionpack (7.0.4)
      actionview (= 7.0.4)
      rack (~> 2.0)
    actionview (7.0.4)
    rack (2.2.4)

PLATFORMS
  ruby

DEPENDENCIES
  actionpack (~> 7.0)
  rails!

BUNDLED WITH
   2.4.10
`)
	wantRelation(t, g, "RubyGems", "actionpack", "7.0.4", relDirect)
	wantRelation(t, g, "RubyGems", "rails", "7.0.4", relDirect)
	wantRelation(t, g, "RubyGems", "rack", "2.2.4", relIndirect)
	wantChains(t, g, "RubyGems", "rack", "actionpack>rack")
}

func TestComposerRequireSkipsPlatformPackages(t *testing.T) {
	g := composerGraph([]byte(`{
	  "packages": [
	    {"name": "monolog/monolog", "version": "2.9.1",
	     "require": {"php": ">=7.2", "ext-json": "*", "psr/log": "^1.0"}}
	  ],
	  "packages-dev": [
	    {"name": "phpunit/phpunit", "version": "9.6.0", "require": {"psr/log": "^1.0"}}
	  ]
	}`))
	wantChains(t, g, "Packagist", "psr/log", "monolog/monolog>psr/log", "phpunit/phpunit>psr/log")
	// `php` and `ext-json` are the runtime, not packages. A chain through
	// "php" explains nothing and Packagist has never heard of it.
	if _, ok := g.requires[ref("Packagist", "php")]; ok {
		t.Error("a platform requirement became a package")
	}
	for _, to := range g.requires[ref("Packagist", "monolog/monolog")] {
		if strings.Contains(to, "ext-") || strings.HasSuffix(to, "/php") {
			t.Errorf("platform requirement kept as an edge: %q", to)
		}
	}
}

func TestPipCompileAnnotations(t *testing.T) {
	g := requirementsGraph(`#
# This file is autogenerated by pip-compile
#
flask==3.0.0
    # via -r requirements.in
click==8.1.7
    # via flask
werkzeug==3.0.1
    # via
    #   flask
    #   quart
`)
	wantRelation(t, g, "PyPI", "flask", "3.0.0", relDirect)
	wantRelation(t, g, "PyPI", "click", "8.1.7", relIndirect)
	wantChains(t, g, "PyPI", "click", "flask>click")
	// Two sources, two explanations. Both are true and the report shows both
	// rather than picking one.
	wantChains(t, g, "PyPI", "werkzeug", "flask>werkzeug", "quart>werkzeug")
}

// A requirements.txt is three different files wearing one name. Only
// pip-compile's records the structure, and the other two have to read as
// silence rather than as "everything here is direct".
func TestPlainRequirementsStatesNothing(t *testing.T) {
	g := requirementsGraph(`flask==3.0.0
click==8.1.7
# a note somebody left about the pin above
jinja2==3.1.2
`)
	if len(g.direct) != 0 || len(g.indirect) != 0 || len(g.requires) != 0 {
		t.Errorf("an unannotated requirements.txt was read as stating something: %+v", g)
	}
}

func TestCycloneDXDependencyGraph(t *testing.T) {
	g := sbomGraph([]byte(`{
	  "bomFormat": "CycloneDX",
	  "specVersion": "1.5",
	  "metadata": { "component": { "bom-ref": "root", "name": "demo", "type": "application" } },
	  "components": [
	    {"bom-ref": "pkg:npm/express@4.17.1", "name": "express", "version": "4.17.1", "purl": "pkg:npm/express@4.17.1"},
	    {"bom-ref": "pkg:npm/qs@6.7.0", "name": "qs", "version": "6.7.0", "purl": "pkg:npm/qs@6.7.0"}
	  ],
	  "dependencies": [
	    {"ref": "root", "dependsOn": ["pkg:npm/express@4.17.1"]},
	    {"ref": "pkg:npm/express@4.17.1", "dependsOn": ["pkg:npm/qs@6.7.0"]}
	  ]
	}`))
	wantRelation(t, g, "npm", "express", "4.17.1", relDirect)
	wantRelation(t, g, "npm", "qs", "6.7.0", relIndirect)
	wantChains(t, g, "npm", "qs", "express>qs")
}

// A cycle is ordinary in an npm or Cargo graph. A walk that did not say so
// would not terminate, and one that dropped the chain would leave every
// package inside the cycle with no explanation at all.
func TestACycleTerminatesAndStillExplains(t *testing.T) {
	g := newGraph()
	g.require(ref("npm", "a"), ref("npm", "b"))
	g.require(ref("npm", "b"), ref("npm", "c"))
	g.require(ref("npm", "c"), ref("npm", "a"))

	got := chains(t, g, "npm", "c")
	if len(got) == 0 {
		t.Fatal("a package inside a cycle got no explanation")
	}
	for _, c := range got {
		if !strings.Contains(c, deeper) {
			t.Errorf("a chain that never reached a top is not marked as cut: %q", c)
		}
	}
}

// The shortest explanation is the one somebody can act on soonest.
func TestTheShortestChainWins(t *testing.T) {
	g := newGraph()
	g.direct[ref("npm", "top")] = true
	g.require(ref("npm", "top"), ref("npm", "mid"))
	g.require(ref("npm", "mid"), ref("npm", "leaf"))
	g.require(ref("npm", "top"), ref("npm", "leaf"))

	got := g.via(ref("npm", "leaf"), maxWhyChains, maxWhyDepth)
	if len(got) == 0 {
		t.Fatal("no chain found")
	}
	if len(got[0]) != 2 {
		t.Errorf("the first chain should be the shortest, got %v", got[0])
	}
}

// A chain cut by the depth bound and a chain that reached the top render
// identically otherwise, and one of them is a claim about where a dependency
// came from.
func TestADeepChainSaysItWasCut(t *testing.T) {
	g := newGraph()
	prev := ref("npm", "p0")
	for i := 1; i <= maxWhyDepth+3; i++ {
		next := ref("npm", "p"+string(rune('0'+i)))
		g.require(prev, next)
		prev = next
	}
	got := g.via(prev, 1, maxWhyDepth)
	if len(got) != 1 {
		t.Fatalf("want one chain, got %d", len(got))
	}
	if got[0][0] != deeper {
		t.Errorf("a chain cut at the depth bound is not marked: %v", got[0])
	}
	if len(got[0]) != maxWhyDepth+1 {
		t.Errorf("the depth bound did not hold: %v", got[0])
	}
}

// PEP 503: names compare case-insensitively with -, _ and . equivalent. The
// formats really do spell one package two ways in one file.
func TestPyPINamesAreNormalised(t *testing.T) {
	for _, tc := range []struct{ in, want string }{
		{"Jinja2", "jinja2"},
		{"typing_extensions", "typing-extensions"},
		{"zope.interface", "zope-interface"},
		{"ruamel.yaml.clib", "ruamel-yaml-clib"},
		{"Flask", "flask"},
	} {
		if got := normalizePyPI(tc.in); got != tc.want {
			t.Errorf("normalizePyPI(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
	// npm is case-sensitive and Go module paths certainly are: normalising
	// them would merge packages that are not the same package.
	if got := ref("npm", "Base64"); got != "npm/Base64" {
		t.Errorf("npm name was normalised: %q", got)
	}
}

// The union rule, and which side wins it: in a monorepo a package can be one
// workspace's own dependency and another's transitive one, and "somebody here
// asked for this by name" is the answer that changes what you do about it.
func TestMergePrefersDirect(t *testing.T) {
	a := newGraph()
	a.indirect[ref("npm", "lodash")] = true
	b := newGraph()
	b.direct[ref("npm", "lodash")] = true

	g := newGraph()
	g.merge(a)
	g.merge(b)
	wantRelation(t, g, "npm", "lodash", "4.17.20", relDirect)
}

// A lockfile is untrusted input, and a dependency graph is a shape somebody
// else chose. The walk has to cost what rta decided it costs — not what the
// file's author did.
func TestTheWalkIsBoundedOnAHostileShape(t *testing.T) {
	// Every package requires every package in the level below it, so the
	// number of distinct chains to the bottom grows as the product of the
	// widths. Nothing here is direct, so nothing terminates early.
	const levels, width = 40, 40
	g := newGraph()
	for l := 0; l < levels-1; l++ {
		for i := 0; i < width; i++ {
			for j := 0; j < width; j++ {
				g.require(ref("npm", "l"+itoa(l)+"n"+itoa(i)), ref("npm", "l"+itoa(l+1)+"n"+itoa(j)))
			}
		}
	}
	done := make(chan int, 1)
	go func() { done <- len(g.via(ref("npm", "l39n0"), maxWhyChains, maxWhyDepth)) }()
	select {
	case n := <-done:
		if n > maxWhyChains {
			t.Errorf("the chain bound did not hold: %d chains", n)
		}
	case <-time.After(10 * time.Second):
		t.Fatal("via did not terminate on a wide graph")
	}
}

func itoa(n int) string { return strconv.Itoa(n) }

// The words a finding uses, because they are what decides the next hour:
// "direct" means bump a version in a file you own, "pulled in by express"
// means the fix belongs to express.
func TestWhereFromSaysWhatToDoNext(t *testing.T) {
	g := newGraph()
	g.direct[ref("npm", "express")] = true
	g.indirect[ref("npm", "qs")] = true
	g.indirect[ref("npm", "orphan")] = true
	g.require(ref("npm", "express"), ref("npm", "qs"))

	for _, tc := range []struct {
		name, want string
	}{
		{"express", "a direct dependency"},
		{"qs", "indirect, pulled in by express"},
		// Listed as indirect and nothing requires it: some formats state the
		// split without recording the edges. Half an answer beats none, and
		// beats an invented chain by more.
		{"orphan", "indirect"},
		// Neither stated nor reachable. Silence is the honest answer.
		{"stranger", ""},
	} {
		got := whereFrom(inventory{structure: g}, component{ecosystem: "npm", name: tc.name})
		if got != tc.want {
			t.Errorf("whereFrom(%s) = %q, want %q", tc.name, got, tc.want)
		}
	}
}

func TestWhereFromShowsEveryExplanationItFound(t *testing.T) {
	g := newGraph()
	g.indirect[ref("npm", "lodash")] = true
	g.require(ref("npm", "express"), ref("npm", "lodash"))
	g.require(ref("npm", "jest"), ref("npm", "lodash"))

	got := whereFrom(inventory{structure: g}, component{ecosystem: "npm", name: "lodash"})
	for _, want := range []string{"express", "jest", "also by"} {
		if !strings.Contains(got, want) {
			t.Errorf("whereFrom = %q, missing %q", got, want)
		}
	}
}

// The command is chosen from the manifest, not the ecosystem: a JavaScript
// project's ecosystem is "npm" whichever of four package managers put the
// tree there, and `npm why` in a pnpm repository is a wasted paste.
func TestWhyCommandFollowsTheLockfile(t *testing.T) {
	for _, tc := range []struct {
		source, ecosystem, want string
	}{
		{"/x/go.mod", "Go", "go mod why -m lodash"},
		{"/x/pnpm-lock.yaml", "npm", "pnpm why lodash"},
		{"/x/yarn.lock", "npm", "yarn why lodash"},
		{"/x/bun.lock", "npm", "bun pm why lodash"},
		{"/x/package-lock.json", "npm", "npm why lodash"},
		{"/x/Cargo.lock", "crates.io", "cargo tree --invert --package lodash"},
		{"/x/uv.lock", "PyPI", "uv tree --invert --package lodash"},
		{"/x/composer.lock", "Packagist", "composer depends lodash"},
		// An SBOM names no package manager, so the ecosystem is the coarser
		// answer and it is still better than none.
		{"/x/bom.json", "npm", "npm why lodash"},
		{"/x/bom.json", "Maven", "mvn dependency:tree -Dincludes=lodash"},
		{"/x/bom.json", "", ""},
	} {
		got := whyCommand(component{name: "lodash", ecosystem: tc.ecosystem, source: tc.source})
		if got != tc.want {
			t.Errorf("whyCommand(%s, %s) = %q, want %q", tc.source, tc.ecosystem, got, tc.want)
		}
	}
}

func TestStructureSummaryCountsWhatWasStated(t *testing.T) {
	g := newGraph()
	g.direct[ref("Go", "a")] = true
	g.indirect[ref("Go", "b")] = true
	inv := inventory{
		all: []component{
			{ecosystem: "Go", name: "a"}, {ecosystem: "Go", name: "b"}, {ecosystem: "Go", name: "c"},
		},
		structure: g,
	}
	if got := structureSummary(inv); got != " — 1 asked for by name, 1 pulled in, 1 not stated" {
		t.Errorf("structureSummary = %q", got)
	}
	// Nothing stated is nothing said: a line reading "0 asked for by name"
	// would be a claim about a file that never mentioned the distinction.
	if got := structureSummary(inventory{all: inv.all, structure: newGraph()}); got != "" {
		t.Errorf("structureSummary with a silent manifest = %q", got)
	}
}

// End to end from files on disk, because the two parsers meeting in
// parseManifest is where a working scanner and a working graph extractor can
// still fail to describe the same package: they key on the name, and one of
// them normalising while the other does not is invisible in either test.
func TestProvenanceReachesTheFinding(t *testing.T) {
	dir := t.TempDir()
	write := func(name, body string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	write("package-lock.json", `{
	  "lockfileVersion": 3,
	  "packages": {
	    "": { "dependencies": { "express": "^4.17.1" } },
	    "node_modules/express": { "version": "4.17.1", "dependencies": { "qs": "6.7.0" } },
	    "node_modules/qs": { "version": "6.7.0" }
	  }
	}`)
	write("go.mod", "module example.com/x\n\ngo 1.24\n\nrequire (\n\tgithub.com/a/b v1.0.0\n\tgithub.com/c/d v2.0.0 // indirect\n)\n")

	fsys := os.DirFS(dir)
	names := manifestsIn(fsys, ".")
	inv := read(fsys, names, names)
	if len(inv.all) != 4 {
		t.Fatalf("read %d components, want 4: %+v", len(inv.all), inv.all)
	}
	r := &report{}
	gradeDeps(r, inv, map[string][]string{
		"npm/qs@6.7.0":             {"GHSA-qs"},
		"Go/github.com/c/d@v2.0.0": {"GHSA-cd"},
	}, nil, false, false)

	qs := mustFind(t, r, "qs")
	if !strings.Contains(qs.detail, "indirect, pulled in by express") {
		t.Errorf("qs finding does not say where it came from: %q", qs.detail)
	}
	// go.mod states the split and records no edges, so this is the half-answer
	// case reaching a real report.
	cd := mustFind(t, r, "github.com/c/d")
	if !strings.Contains(cd.detail, "indirect") || strings.Contains(cd.detail, "pulled in by") {
		t.Errorf("a go.mod indirect should be stated without an invented chain: %q", cd.detail)
	}
	// And the report says so, with the command that does have the chain.
	prov := mustFind(t, r, "provenance")
	if !strings.Contains(prov.detail, "go mod why -m github.com/c/d") {
		t.Errorf("provenance finding does not hand over the command: %q", prov.detail)
	}
	count := mustFind(t, r, "dependencies")
	if !strings.Contains(count.detail, "2 asked for by name, 2 pulled in") {
		t.Errorf("inventory line does not split the count: %q", count.detail)
	}
}

// A source string is not a bag of substrings.
//
// isLocalSource matched "path" anywhere in the text it was handed, and it was
// handed the source — so a crate from a git remote whose URL happens to
// contain the word read as "a directory on this machine" and was dropped from
// the inventory entirely: never sent to OSV, never counted, never mentioned. A
// shorter report that looks complete is the worst failure this file has.
func TestAURLContainingAMarkerWordIsNotALocalSource(t *testing.T) {
	const cargo = `[[package]]
name = "app"
version = "0.1.0"
dependencies = ["helper"]

[[package]]
name = "helper"
version = "1.0.0"
source = "git+https://github.com/acme/pathfinder?branch=main#deadbeef"
checksum = "aaa"
dependencies = ["serde"]

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbb"
`
	// The component parser: the crate has to reach the inventory at all.
	var got []string
	for _, c := range parseTOMLLock(cargo, "Cargo.lock", "crates.io", true) {
		got = append(got, c.name)
	}
	sort.Strings(got)
	if !reflect.DeepEqual(got, []string{"helper", "serde"}) {
		t.Errorf("inventory = %v, want both crates — one was read as a local directory", got)
	}

	// And the graph: helper is a dependency of app, not the project.
	g := tomlGraph(cargo, "crates.io", cargoLock)
	wantRelation(t, g, "crates.io", "helper", "1.0.0", relDirect)    // app requires it
	wantRelation(t, g, "crates.io", "serde", "1.0.197", relIndirect) // helper does
	wantChains(t, g, "crates.io", "serde", "helper>serde")
}

// A private index whose name contains a marker word is the same defect on the
// Python side.
func TestAPrivateIndexIsNotALocalSource(t *testing.T) {
	g := tomlGraph(`[[package]]
name = "demo"
version = "0.1.0"
source = { virtual = "." }
dependencies = [
    { name = "internal-lib" },
]

[[package]]
name = "internal-lib"
version = "1.0.0"
source = { registry = "https://nexus.corp/repository/pypi-pathways/simple" }
dependencies = [
    { name = "requests" },
]

[[package]]
name = "requests"
version = "2.31.0"
source = { registry = "https://pypi.org/simple" }
`, "PyPI", uvLock)
	wantRelation(t, g, "PyPI", "internal-lib", "1.0.0", relDirect)
	wantRelation(t, g, "PyPI", "requests", "2.31.0", relIndirect)
	wantChains(t, g, "PyPI", "requests", "internal-lib>requests")
}

// poetry.lock has no record for the project, so one path dependency must not
// make the whole file claim a direct/indirect split it never states. Getting
// this wrong inverted both directions at once: a genuine top-level dependency
// read as somebody else's problem, and a sibling library's dependency read as
// the project's own.
func TestAPoetryPathDependencyDoesNotInventADirectSet(t *testing.T) {
	g := tomlGraph(`[[package]]
name = "flask"
version = "3.0.0"
files = []

[package.dependencies]
click = ">=8.0"

[[package]]
name = "mylib"
version = "0.1.0"
files = []

[package.dependencies]
requests = ">=2.0"

[package.source]
type = "directory"
url = "../mylib"

[[package]]
name = "requests"
version = "2.31.0"
files = []

[[package]]
name = "click"
version = "8.1.7"
files = []
`, "PyPI", poetryLock)
	versions := map[string]string{"flask": "3.0.0", "requests": "2.31.0", "click": "8.1.7"}
	for _, name := range []string{"flask", "requests", "click"} {
		wantRelation(t, g, "PyPI", name, versions[name], relUnstated)
	}
	// The edges are still read — a path dependency is how its own
	// dependencies got into the tree.
	wantChains(t, g, "PyPI", "requests", "mylib>requests")
	wantChains(t, g, "PyPI", "click", "flask>click")
}

// A Berry `patch:` resolution embeds a second name@range inside itself, so the
// last `@` is not the separator. The name came out as a package that does not
// exist, printed as the cause of a vulnerability.
func TestABerryPatchResolutionKeepsItsRealName(t *testing.T) {
	g := yarnGraph(`__metadata:
  version: 8

"demo@workspace:.":
  version: 0.0.0-use.local
  dependencies:
    fsevents: "patch:fsevents@npm%3A2.3.2#optional!builtin<compat/fsevents>"

"fsevents@patch:fsevents@npm%3A2.3.2#optional!builtin<compat/fsevents>":
  version: 2.3.2
  dependencies:
    node-gyp: "npm:^9.0.0"

"@scope/pkg@patch:@scope/pkg@npm%3A1.0.0#./p.patch":
  version: 1.0.0
  dependencies:
    tslib: "npm:^2.0.0"
`)
	wantChains(t, g, "npm", "node-gyp", "fsevents>node-gyp")
	wantChains(t, g, "npm", "tslib", "@scope/pkg>tslib")
	for from := range g.requires {
		if strings.Contains(from, "patch:") {
			t.Errorf("a resolution leaked into a package name: %q", from)
		}
	}
}

// pip-tools writes the project's own name when a requirement came from
// pyproject.toml rather than an input file. Read as an edge it invented a
// package named after a filename, and left the dependency marked indirect.
func TestPipCompileProjectSourceIsDirect(t *testing.T) {
	g := requirementsGraph(`#
# This file is autogenerated by pip-compile
#
flask==3.0.0
    # via myproject (pyproject.toml)
click==8.1.7
    # via flask
`)
	wantRelation(t, g, "PyPI", "flask", "3.0.0", relDirect)
	wantRelation(t, g, "PyPI", "click", "8.1.7", relIndirect)
	for from := range g.requires {
		if strings.Contains(from, "pyproject") || strings.Contains(from, "myproject") {
			t.Errorf("a filename became a package: %q", from)
		}
	}
}

// "via" as a word, not as a prefix. `# viable replacement pending` made an
// edge from a package called "ble replacement pending" — and set the flag
// that switches the whole file from "states nothing" to "states a graph",
// which turns every other line's silence into "indirect".
func TestAHumanCommentIsNotAnAnnotation(t *testing.T) {
	g := requirementsGraph(`click==8.1.7
    # viable replacement pending
jinja2==3.1.2
    # vital, do not bump
`)
	if len(g.direct) != 0 || len(g.indirect) != 0 || len(g.requires) != 0 {
		t.Errorf("human comments were read as structure: %+v", g)
	}
}

// A workspace link entry is a symlink, not an installed copy.
func TestAWorkspaceLinkIsNotAnInstalledPackage(t *testing.T) {
	g := npmLockGraph([]byte(`{
	  "lockfileVersion": 3,
	  "packages": {
	    "": { "dependencies": { "express": "^4.17.1" }, "workspaces": ["packages/*"] },
	    "packages/app": { "name": "@acme/app", "dependencies": { "lodash": "^4.0.0" } },
	    "node_modules/@acme/app": { "resolved": "packages/app", "link": true },
	    "node_modules/express": { "version": "4.17.1" },
	    "node_modules/lodash": { "version": "4.17.21" }
	  }
	}`))
	if g.indirect[ref("npm", "@acme/app")] {
		t.Error("the project's own workspace package was marked indirect")
	}
}

// The same edge arrives by ordinary routes — a dependency named in both
// `dependencies` and `optionalDependencies`, or an SBOM merged with the
// lockfile it was generated from, which manifest.go calls the normal case.
func TestAnEdgeIsRecordedOnce(t *testing.T) {
	g := npmLockGraph([]byte(`{
	  "lockfileVersion": 3,
	  "packages": {
	    "": { "dependencies": { "express": "^4.17.1" } },
	    "node_modules/express": { "version": "4.17.1",
	      "dependencies": { "qs": "6.7.0" },
	      "optionalDependencies": { "qs": "6.7.0" },
	      "peerDependencies": { "qs": "6.7.0" } },
	    "node_modules/qs": { "version": "6.7.0" }
	  }
	}`))
	if got := g.requires[ref("npm", "express")]; len(got) != 1 {
		t.Errorf("express requires %v, want qs once", got)
	}
	// And merging a graph with itself does not double it either.
	before := g.edges()
	g.merge(g)
	if g.edges() != before {
		t.Errorf("merging duplicated %d edges", g.edges()-before)
	}
}

// The edge budget is checked on every insert, so computing it by walking the
// map made construction quadratic: 0.4 s for 25,000 edges, 1.6 s for 50,000,
// 6.1 s for 100,000 — meaning the bound itself permitted around twenty-five
// seconds of pure map-walking on the happy path of a large pnpm monorepo.
//
// A wall clock in a -race -shuffle suite measures the machine as much as the
// code, so the ceiling here is deliberately enormous: the linear version does
// this in about fifteen milliseconds, and the quadratic one could not have met
// two seconds on any machine.
func TestBuildingTheGraphIsNotQuadratic(t *testing.T) {
	g := newGraph()
	start := time.Now()
	for i := 0; i < 20000; i++ {
		from := ref("npm", "p"+strconv.Itoa(i))
		for j := 0; j < 5; j++ {
			g.require(from, ref("npm", "d"+strconv.Itoa(i)+"-"+strconv.Itoa(j)))
		}
	}
	if elapsed := time.Since(start); elapsed > 2*time.Second {
		t.Errorf("100,000 edges took %v — the count is being recomputed per insert", elapsed)
	}
	if g.edges() != 100000 {
		t.Errorf("edges = %d, want 100000", g.edges())
	}
}

// A project asks for one version of a package and the tree holds three. Keyed
// on the name, all three were reported as "a direct dependency" — so an
// advisory against a copy something else dragged in sent somebody to bump a
// version in a package.json that has nothing to do with it.
//
// Found by running the parsers against real lockfiles rather than fixtures:
// nine such components in one, twelve in another. The npm-family formats all
// state the resolved version of a direct dependency, so this is exactness
// rather than a retreat.
func TestOnlyTheCopyTheProjectAskedForIsDirect(t *testing.T) {
	t.Run("bun", func(t *testing.T) {
		g := bunGraph([]byte(`{
		  "lockfileVersion": 1,
		  "workspaces": { "": { "name": "demo", "dependencies": { "commander": "^15.0.0" } } },
		  "packages": {
		    "commander": ["commander@15.0.0", "", {}, "sha512-a"],
		    "d3-dsv/commander": ["commander@7.2.0", "", {}, "sha512-b"],
		    "katex/commander": ["commander@8.3.0", "", {}, "sha512-c"]
		  }
		}`))
		wantRelation(t, g, "npm", "commander", "15.0.0", relDirect)
		wantRelation(t, g, "npm", "commander", "7.2.0", relIndirect)
		wantRelation(t, g, "npm", "commander", "8.3.0", relIndirect)
	})

	t.Run("npm", func(t *testing.T) {
		g := npmLockGraph([]byte(`{
		  "lockfileVersion": 3,
		  "packages": {
		    "": { "dependencies": { "vite": "^8.0.0" } },
		    "node_modules/vite": { "version": "8.1.5" },
		    "node_modules/vitepress/node_modules/vite": { "version": "5.4.21" },
		    "node_modules/vitepress": { "version": "1.6.4", "dependencies": { "vite": "^5.0.0" } }
		  }
		}`))
		wantRelation(t, g, "npm", "vite", "8.1.5", relDirect)
		wantRelation(t, g, "npm", "vite", "5.4.21", relIndirect)
	})

	t.Run("pnpm", func(t *testing.T) {
		g := pnpmGraph(`lockfileVersion: '9.0'

importers:

  .:
    dependencies:
      vite:
        specifier: ^8.0.0
        version: 8.1.5(@types/node@20.11.0)

snapshots:

  vite@8.1.5(@types/node@20.11.0): {}

  vite@5.4.21: {}
`)
		wantRelation(t, g, "npm", "vite", "8.1.5", relDirect)
		wantRelation(t, g, "npm", "vite", "5.4.21", relIndirect)
	})

	t.Run("yarn berry", func(t *testing.T) {
		g := yarnGraph(`__metadata:
  version: 8

"demo@workspace:.":
  version: 0.0.0-use.local
  dependencies:
    vite: "npm:^8.0.0"

"vite@npm:^8.0.0":
  version: 8.1.5

"vite@npm:^5.0.0":
  version: 5.4.21
`)
		wantRelation(t, g, "npm", "vite", "8.1.5", relDirect)
		wantRelation(t, g, "npm", "vite", "5.4.21", relIndirect)
	})
}

// The version-exact pinning above, applied to a workspace repository, said
// "indirect" about dependencies a workspace's own package.json names.
//
// **Because only one copy of a package is hoisted to the top, and it is not
// necessarily the one being looked at.** Two workspaces asking for `commander`
// at `^7.2.0` and `^11.0.0` get one copy at the top and one nested beside
// whichever workspace lost; the parsers pinned the hoisted copy for *every*
// declaration of the name, so the nested one — declared, by name, one
// directory down — was reported as somebody else's problem. Worse where the
// top-level copy is purely transitive: a copy nobody asked for reads "direct"
// while the declared one reads "indirect", both answers inverted.
//
// The fixtures are the bytes npm 11 and bun 1.4 actually wrote for the layout
// in each subtest's name, not hand-built approximations — the previous round
// of this bug survived a fixture and was caught by a real lockfile, and bun's
// key for a nested copy turned out to be the holder's *package name*
// (`@acme/toolkit/commander`), which no amount of reasoning about paths would
// have produced.
func TestAWorkspacesOwnDependencyIsDirectWhereverItLanded(t *testing.T) {
	// npm nests the loser beside the workspace that asked: Node's own
	// resolution, walked upward from the declaring manifest.
	t.Run("npm", func(t *testing.T) {
		g := npmLockGraph([]byte(`{
		  "name": "root",
		  "lockfileVersion": 3,
		  "packages": {
		    "": {},
		    "node_modules/@acme/app": { "link": true, "resolved": "packages/app" },
		    "node_modules/@acme/toolkit": { "link": true, "resolved": "packages/toolkit" },
		    "node_modules/commander": { "version": "7.2.0" },
		    "packages/app": { "version": "1.0.0", "dependencies": { "commander": "^7.2.0" } },
		    "packages/toolkit": { "version": "1.0.0", "dependencies": { "commander": "^11.0.0" } },
		    "packages/toolkit/node_modules/commander": { "version": "11.1.0" }
		  }
		}`))
		wantRelation(t, g, "npm", "commander", "7.2.0", relDirect)
		wantRelation(t, g, "npm", "commander", "11.1.0", relDirect)
	})

	// bun keys the nested copy by the holding package's name.
	t.Run("bun", func(t *testing.T) {
		g := bunGraph([]byte(`{
		  "lockfileVersion": 2,
		  "workspaces": {
		    "": { "name": "root" },
		    "packages/app": { "name": "@acme/app", "dependencies": { "commander": "^7.2.0" } },
		    "packages/toolkit": { "name": "@acme/toolkit", "dependencies": { "commander": "^11.0.0" } }
		  },
		  "packages": {
		    "@acme/app": ["@acme/app@workspace:packages/app"],
		    "@acme/toolkit": ["@acme/toolkit@workspace:packages/toolkit"],
		    "commander": ["commander@7.2.0", "", {}, "sha512-a"],
		    "@acme/toolkit/commander": ["commander@11.1.0", "", {}, "sha512-b"]
		  }
		}`))
		wantRelation(t, g, "npm", "commander", "7.2.0", relDirect)
		wantRelation(t, g, "npm", "commander", "11.1.0", relDirect)
	})

	// The root declaring it too pushes *both* workspaces to nested copies, and
	// bun writes the root's under the bare name rather than under "root" — so
	// all three are direct and the parser must not look for "root/commander".
	t.Run("bun, root declares as well", func(t *testing.T) {
		g := bunGraph([]byte(`{
		  "lockfileVersion": 2,
		  "workspaces": {
		    "": { "name": "root", "dependencies": { "commander": "^9.0.0" } },
		    "packages/app": { "name": "@acme/app", "dependencies": { "commander": "^7.2.0" } },
		    "packages/toolkit": { "name": "@acme/toolkit", "dependencies": { "commander": "^11.0.0" } }
		  },
		  "packages": {
		    "@acme/app": ["@acme/app@workspace:packages/app"],
		    "@acme/toolkit": ["@acme/toolkit@workspace:packages/toolkit"],
		    "commander": ["commander@9.5.0", "", {}, "sha512-a"],
		    "@acme/app/commander": ["commander@7.2.0", "", {}, "sha512-b"],
		    "@acme/toolkit/commander": ["commander@11.1.0", "", {}, "sha512-c"]
		  }
		}`))
		for _, v := range []string{"9.5.0", "7.2.0", "11.1.0"} {
			wantRelation(t, g, "npm", "commander", v, relDirect)
		}
	})

	// A copy nothing declared is still indirect: the fix must not turn the pin
	// into "every copy is direct", which would lose the whole point of it.
	t.Run("an undeclared copy stays indirect", func(t *testing.T) {
		g := npmLockGraph([]byte(`{
		  "lockfileVersion": 3,
		  "packages": {
		    "": {},
		    "packages/app": { "version": "1.0.0", "dependencies": { "commander": "^7.2.0" } },
		    "node_modules/commander": { "version": "7.2.0" },
		    "node_modules/katex": { "version": "0.16.9", "dependencies": { "commander": "^8.0.0" } },
		    "node_modules/katex/node_modules/commander": { "version": "8.3.0" }
		  }
		}`))
		wantRelation(t, g, "npm", "commander", "7.2.0", relDirect)
		wantRelation(t, g, "npm", "commander", "8.3.0", relIndirect)
	})
}

// A pnpm project that is not a monorepo states its direct set at column zero,
// and reading only `importers:` missed all of it.
//
// v5 and v6 omit `importers:` for a single project and write the root's own
// `dependencies:` at the top level instead — one indentation level up from the
// monorepo shape the scanner was built around. Every package in such a file
// came back "the format did not say" while the format said it on line three.
// Caught by running the parser over a real vitepress project: 88 components,
// not one relation among them, and the answer was `vitepress` all along.
func TestAPnpmProjectStatesItsDirectSetWithoutAnImportersBlock(t *testing.T) {
	// v6 puts the resolved version on its own line under the name.
	t.Run("v6", func(t *testing.T) {
		g := pnpmGraph(`lockfileVersion: '6.0'

devDependencies:
  vitepress:
    specifier: ^1.0.0-alpha.75
    version: 1.0.0-alpha.75(@algolia/client-search@4.17.0)

packages:

  /vitepress@1.0.0-alpha.75:
    resolution: {integrity: sha512-a}
    dependencies:
      '@algolia/autocomplete-core': 1.8.2
    dev: true

  /@algolia/autocomplete-core@1.8.2:
    resolution: {integrity: sha512-b}
    dev: true
`)
		wantRelation(t, g, "npm", "vitepress", "1.0.0-alpha.75", relDirect)
		wantRelation(t, g, "npm", "@algolia/autocomplete-core", "1.8.2", relIndirect)
	})

	// v5 writes it inline beside the name.
	t.Run("v5", func(t *testing.T) {
		g := pnpmGraph(`lockfileVersion: 5.4

dependencies:
  express: 4.17.1
devDependencies:
  vite: 4.0.0_@types+node@20.11.0

packages:

  /express/4.17.1:
    resolution: {integrity: sha512-a}
    dependencies:
      qs: 6.7.0

  /qs/6.7.0:
    resolution: {integrity: sha512-b}

  /vite/4.0.0:
    resolution: {integrity: sha512-c}
    dev: true
`)
		wantRelation(t, g, "npm", "express", "4.17.1", relDirect)
		wantRelation(t, g, "npm", "vite", "4.0.0", relDirect)
		wantRelation(t, g, "npm", "qs", "6.7.0", relIndirect)
	})

	// A monorepo must not be read twice: its workspace dependency lines sit
	// under `importers:` at indent four, and a top-level `dependencies:` key
	// inside some other block is not a root importer.
	t.Run("a monorepo is unaffected", func(t *testing.T) {
		g := pnpmGraph(`lockfileVersion: '9.0'

importers:

  packages/app:
    dependencies:
      vite:
        specifier: ^8.0.0
        version: 8.1.5

snapshots:

  vite@8.1.5: {}

  vite@5.4.21: {}
`)
		wantRelation(t, g, "npm", "vite", "8.1.5", relDirect)
		wantRelation(t, g, "npm", "vite", "5.4.21", relIndirect)
	})
}

// A declaration nothing in the tree answers disqualifies the *name* from being
// pinned, rather than being quietly skipped.
//
// An optional dependency skipped on this platform, or a tree installed with
// `--omit=dev`, leaves a workspace's declaration with no copy to point at
// while a sibling workspace's copy sits nested under itself, out of the
// missing one's reach. Pinning on the strength of the declarations that *did*
// resolve would make relation answer "indirect" for every copy the incomplete
// pin does not name — a version-exact statement read out of a file that turned
// out not to make it. Falling back to the name-keyed answer is the honest
// move, and that answer is already withheld when the tree holds two copies.
func TestAnUnresolvableDeclarationDisqualifiesThePin(t *testing.T) {
	g := npmLockGraph([]byte(`{
	  "lockfileVersion": 3,
	  "packages": {
	    "": {},
	    "packages/app": { "version": "1.0.0", "dependencies": { "commander": "^7.2.0" } },
	    "packages/app/node_modules/commander": { "version": "7.2.0" },
	    "packages/toolkit": { "version": "1.0.0", "devDependencies": { "commander": "^11.0.0" } }
	  }
	}`))
	r := ref("npm", "commander")
	if !g.direct[r] {
		t.Fatal("commander is not direct at all")
	}
	if g.pinned[r] {
		t.Error("commander was pinned although one of its two declarations resolved to nothing")
	}
	// Name-keyed still: a lone copy is direct, and a second copy makes it say
	// nothing rather than guess.
	wantRelation(t, g, "npm", "commander", "7.2.0", relDirect)
	ambiguous := map[string]bool{r: true}
	if got := g.relation(component{ecosystem: "npm", name: "commander", version: "7.2.0"}, ambiguous); got != relUnstated {
		t.Errorf("with two copies: %q, want it to say nothing", describe(got))
	}
}

// One manifest's pin may not answer for another manifest's package.
//
// A scan covering two projects — one with a package-lock.json, which states
// the resolved version of a direct dependency, and one with a yarn v1 lockfile
// or a composer.json, which does not — merged the two graphs and unioned the
// pins. relation then took the pinned branch for the second project's copy and
// answered "indirect", a version-exact statement neither file made, and the
// safeguard for ambiguous names was unreachable because it sits on the
// unpinned path.
func TestAPinFromOneManifestDoesNotSpeakForAnother(t *testing.T) {
	pinned := newGraph()
	pinned.pin(ref("npm", "commander"), "15.0.0")

	nameOnly := newGraph()
	nameOnly.direct[ref("npm", "commander")] = true

	for _, order := range []struct {
		name string
		a, b graph
	}{
		{"pinned first", pinned, nameOnly},
		{"pinned second", nameOnly, pinned},
	} {
		t.Run(order.name, func(t *testing.T) {
			var g graph
			g.merge(order.a)
			g.merge(order.b)
			if g.pinned[ref("npm", "commander")] {
				t.Fatal("a pin survived a merge with a manifest that named the same package without one")
			}
			ambiguous := map[string]bool{ref("npm", "commander"): true}
			c := component{ecosystem: "npm", name: "commander", version: "7.2.0"}
			if got := g.relation(c, ambiguous); got != relUnstated {
				t.Errorf("relation = %q, want it to say nothing", describe(got))
			}
		})
	}

	// Two pinned manifests keep their pins: the merge only steps back where a
	// manifest actually declined to say which version.
	t.Run("both pinned", func(t *testing.T) {
		other := newGraph()
		other.pin(ref("npm", "commander"), "7.2.0")
		var g graph
		g.merge(pinned)
		g.merge(other)
		wantRelation(t, g, "npm", "commander", "15.0.0", relDirect)
		wantRelation(t, g, "npm", "commander", "7.2.0", relDirect)
		wantRelation(t, g, "npm", "commander", "8.3.0", relIndirect)
	})
}

// Where a format does not pin the version, a name-keyed direct set may not be
// repeated about a package the tree holds two of: the project asked for *a*
// commander and this is one of three, and which one is not recorded.
func TestAnAmbiguousNameIsNotClaimedDirect(t *testing.T) {
	g := newGraph()
	g.direct[ref("RubyGems", "rack")] = true
	one := component{ecosystem: "RubyGems", name: "rack", version: "2.2.4"}

	if got := g.relation(one, nil); got != relDirect {
		t.Errorf("with one copy: %q, want direct", describe(got))
	}
	ambiguous := map[string]bool{ref("RubyGems", "rack"): true}
	if got := g.relation(one, ambiguous); got != relUnstated {
		t.Errorf("with two copies: %q, want it to say nothing", describe(got))
	}
}

// And the reader is told, because "pulled in by express" reads as a fact about
// the version in front of them when the file only records the name.
func TestChainsSayWhenTheNameIsAmbiguous(t *testing.T) {
	g := newGraph()
	g.indirect[ref("npm", "lodash")] = true
	g.require(ref("npm", "express"), ref("npm", "lodash"))
	inv := inventory{
		structure: g,
		ambiguous: map[string]bool{ref("npm", "lodash"): true},
		all: []component{
			{ecosystem: "npm", name: "lodash", version: "3.10.1"},
			{ecosystem: "npm", name: "lodash", version: "4.17.21"},
		},
	}
	got := whereFrom(inv, inv.all[0])
	for _, want := range []string{"one of 2 copies here", "pulled in by express"} {
		if !strings.Contains(got, want) {
			t.Errorf("whereFrom = %q, missing %q", got, want)
		}
	}
}
