package audit

import (
	"strings"
	"testing"
)

// want asserts an exact name@version set, because the failure that matters
// here is not "missed one" — it is "read a version the file never stated",
// which turns a clean report into a false negative nobody can see.
func want(t *testing.T, got []component, eco string, pairs ...string) {
	t.Helper()
	seen := map[string]bool{}
	for _, c := range got {
		if c.ecosystem != eco {
			t.Errorf("%s: ecosystem %q, want %q — OSV's names are case-sensitive and a wrong one "+
				"answers with no vulnerabilities rather than an error", c.name, c.ecosystem, eco)
		}
		seen[c.name+"@"+c.version] = true
	}
	for _, p := range pairs {
		if !seen[p] {
			t.Errorf("missing %s; got %v", p, keys(got))
		}
		delete(seen, p)
	}
	for extra := range seen {
		t.Errorf("read %s, which is not a dependency of this project", extra)
	}
}

func keys(cs []component) []string {
	out := make([]string, 0, len(cs))
	for _, c := range cs {
		out = append(out, c.name+"@"+c.version)
	}
	return out
}

// pnpm has shipped three spellings of the same key and projects carry all of
// them, so the parser has to read a lockfile it did not expect the version of.
func TestParsePnpmLockAcrossItsThreeFormats(t *testing.T) {
	v9 := `lockfileVersion: '9.0'

importers:
  .:
    dependencies:
      lodash:
        specifier: ^4.17.21
        version: 4.17.21

packages:

  '@babel/code-frame@7.24.7':
    resolution: {integrity: sha512-abc}
    engines: {node: '>=6.9.0'}

  lodash@4.17.21:
    resolution: {integrity: sha512-def}

  vite@5.0.0(@types/node@20.11.0):
    resolution: {integrity: sha512-ghi}

snapshots:

  lodash@4.17.21: {}
`
	// The peer suffix names which build of vite this is, not which package.
	want(t, parsePnpmLock(v9, "p"), "npm",
		"@babel/code-frame@7.24.7", "lodash@4.17.21", "vite@5.0.0")

	v6 := `lockfileVersion: '6.0'
packages:
  /@babel/code-frame@7.12.11:
    resolution: {integrity: sha512-x}
  /lodash@4.17.21:
    resolution: {integrity: sha512-y}
`
	want(t, parsePnpmLock(v6, "p"), "npm", "@babel/code-frame@7.12.11", "lodash@4.17.21")

	v5 := `lockfileVersion: 5.4
packages:
  /@babel/code-frame/7.12.11:
    resolution: {integrity: sha512-x}
  /lodash/4.17.21:
    resolution: {integrity: sha512-y}
`
	want(t, parsePnpmLock(v5, "p"), "npm", "@babel/code-frame@7.12.11", "lodash@4.17.21")
}

// The two yarn dialects are the same file with different punctuation, and a
// berry lockfile additionally lists the repository's own workspaces — which
// are not dependencies, and which OSV has never heard of.
func TestParseYarnLockBothDialects(t *testing.T) {
	v1 := `# THIS IS AN AUTOGENERATED FILE
# yarn lockfile v1


"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.10.4":
  version "7.12.11"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.12.11.tgz"
  integrity sha512-abc

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
`
	want(t, parseYarnLock(v1, "y"), "npm", "@babel/code-frame@7.12.11", "lodash@4.17.21")

	berry := `__metadata:
  version: 6
  cacheKey: 8

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: abc
  languageName: node

"myapp@workspace:.":
  version: 0.0.0-use.local
  resolution: "myapp@workspace:."
  languageName: unknown
`
	want(t, parseYarnLock(berry, "y"), "npm", "lodash@4.17.21")
}

// bun writes JSONC, which encoding/json rejects outright rather than
// tolerating — so without the strip the whole file reads as zero dependencies.
func TestParseBunLockReadsJSONC(t *testing.T) {
	src := `{
  "lockfileVersion": 1,
  // bun's own writer emits trailing commas; the format allows comments too.
  "workspaces": {
    "": { "name": "myapp" },
    "packages/api": { "name": "@myapp/api" },
  },
  "packages": {
    "lodash": ["lodash@4.17.21", "", {}, "sha512-abc"],
    "@types/node": ["@types/node@20.11.0", "", {}, "sha512-def"],
    "@myapp/api": ["@myapp/api@workspace:packages/api"],
  },
}
`
	got, err := parseBunLock([]byte(src), "b")
	if err != nil {
		t.Fatal(err)
	}
	want(t, got, "npm", "lodash@4.17.21", "@types/node@20.11.0")
}

// A "//" inside a string is a URL. Stripping it as a comment would truncate
// the line and make the whole document unparseable.
func TestStripJSONCLeavesStringsAlone(t *testing.T) {
	src := `{"url": "https://example.com/x", "note": "a /* b */ c"}`
	if got := string(stripJSONC([]byte(src))); got != src {
		t.Errorf("rewrote a document that had no comments in it:\n%s", got)
	}
}

// uv, Poetry and Cargo write the same three lines, and all three record the
// project's own packages alongside its dependencies. Counting those inflates
// the inventory with packages that exist on no registry.
func TestParseTOMLLockSkipsTheProjectsOwnPackages(t *testing.T) {
	uv := `version = 1
requires-python = ">=3.11"

[[package]]
name = "myproject"
version = "0.1.0"
source = { virtual = "." }

[[package]]
name = "requests"
version = "2.31.0"
source = { registry = "https://pypi.org/simple" }

[[package.wheels]]
url = "https://files.pythonhosted.org/x.whl"
hash = "sha256:abc"

[[package]]
name = "urllib3"
version = "2.1.0"
source = { registry = "https://pypi.org/simple" }
`
	want(t, parseTOMLLock(uv, "u", "PyPI", false), "PyPI", "requests@2.31.0", "urllib3@2.1.0")

	poetry := `[[package]]
name = "certifi"
version = "2023.11.17"
description = "Python package for providing Mozilla's CA Bundle."
optional = false
python-versions = ">=3.6"
files = [
    {file = "certifi-2023.11.17-py3-none-any.whl", hash = "sha256:abc"},
]

[package.dependencies]
urllib3 = ">=1.21.1,<3"

[[package]]
name = "localthing"
version = "0.1.0"
optional = false

[package.source]
type = "directory"
url = "../localthing"
`
	want(t, parseTOMLLock(poetry, "p", "PyPI", false), "PyPI", "certifi@2023.11.17")

	// A Cargo workspace member is the entry with no source line at all.
	cargo := `version = 3

[[package]]
name = "myapp"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.195"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"
`
	want(t, parseTOMLLock(cargo, "c", "crates.io", true), "crates.io", "serde@1.0.195")
}

func TestParseComposerAndPipfileAndGemfile(t *testing.T) {
	composer := `{
  "packages": [
    {"name": "monolog/monolog", "version": "v2.9.1"},
    {"name": "psr/log", "version": "3.0.0"}
  ],
  "packages-dev": [
    {"name": "phpunit/phpunit", "version": "v10.5.0"}
  ]
}`
	got, err := parseComposerLock([]byte(composer), "c")
	if err != nil {
		t.Fatal(err)
	}
	// The leading v is composer's spelling, not Packagist's; left on, every
	// lookup silently misses.
	want(t, got, "Packagist", "monolog/monolog@2.9.1", "psr/log@3.0.0", "phpunit/phpunit@10.5.0")

	pipfile := `{
  "default": {"requests": {"version": "==2.31.0"}, "urllib3": {"version": "==2.1.0"}},
  "develop": {"pytest": {"version": "==7.4.3"}}
}`
	got, err = parsePipfileLock([]byte(pipfile), "p")
	if err != nil {
		t.Fatal(err)
	}
	want(t, got, "PyPI", "requests@2.31.0", "urllib3@2.1.0", "pytest@7.4.3")

	gemfile := `GEM
  remote: https://rubygems.org/
  specs:
    actionpack (7.0.4)
      actionview (= 7.0.4)
      rack (~> 2.0, >= 2.2.0)
    rack (2.2.6.4)

PLATFORMS
  ruby

DEPENDENCIES
  rails (~> 7.0)
`
	// Indentation is the grammar: four spaces is a resolved gem, six is one
	// of its requirements and carries a range rather than a version.
	want(t, parseGemfileLock(gemfile, "g"), "RubyGems", "actionpack@7.0.4", "rack@2.2.6.4")
}

// Every one of these formats has somewhere to put a thing that is not a
// version. Sending one to OSV is not an error there — it is an empty answer,
// which on a screen is indistinguishable from "not vulnerable".
func TestIsVersionishRejectsResolutions(t *testing.T) {
	for _, bad := range []string{
		"", "workspace:packages/api", "npm:lodash@4.17.21", "link:../shared",
		">= 4.2", "^7.0.0", "file:../x", "0.0.0-use.local ",
	} {
		if isVersionish(bad) {
			t.Errorf("%q was accepted as a version", bad)
		}
	}
	for _, good := range []string{"1.2.3", "7.24.7", "0.0.0-use.local", "2023.11.17", "2.2.6.4"} {
		if !isVersionish(good) {
			t.Errorf("%q was rejected", good)
		}
	}
}

// A bun project whose only lockfile is binary has dependencies. Reporting
// nothing and saying nothing answers "are we affected?" with a confident no.
func TestBinaryBunLockfileIsAFindingNotASilence(t *testing.T) {
	_, err := parseManifest("bun.lockb")
	if err == nil {
		t.Fatal("bun.lockb must not read as an empty dependency list")
	}
	if !strings.Contains(err.Error(), "--save-text-lockfile") {
		t.Errorf("the error has to say what to do about it: %v", err)
	}
}
