package audit

import (
	"encoding/json"
	"errors"
	"strings"
)

// The lockfiles a working developer actually has.
//
// The first version of this read go.mod, package-lock.json and
// requirements.txt, which between them cover a shrinking share of real
// projects: npm has three serious competitors, and uv is on its way to being
// the Python default. A dependency audit that silently finds nothing in a
// pnpm monorepo is worse than one that refuses to run, because "0 advisories"
// and "0 dependencies read" look identical on a screen and only one of them
// is good news.
//
// Every parser here obeys manifest.go's rule: extract a name, a version and
// an ecosystem, ignore the rest, skip what is not understood. None of them
// pulls in a YAML or TOML dependency to do it. That is not only about binary
// size — a lockfile is generated by a program, so its shape is rigid in
// exactly the way hand-written config is not, and a line scanner that reads
// the two fields it needs cannot be wrong about the ninety it ignores.

// errBinaryLockfile is what a lockfile nothing can read reports. It is a
// finding rather than a silence: a bun project whose only lockfile is binary
// has dependencies, and a report that omits them while saying nothing has
// answered "are we affected?" with a confident no.
var errBinaryLockfile = errors.New(
	"binary lockfile — run `bun install --save-text-lockfile` to write bun.lock, which this reads")

// parsePnpmLock reads the keys of the top-level `packages:` block, which is
// the one thing every pnpm lockfile version agrees on. Three spellings have
// shipped and projects still carry all of them:
//
//	v5    /@babel/code-frame/7.24.7
//	v6    /@babel/code-frame@7.24.7
//	v9    '@babel/code-frame@7.24.7'
//
// plus a peer-dependency suffix — `vite@5.0.0(@types/node@20.11.0)` — that
// names the resolution, not the package, and has to come off before the
// version does.
func parsePnpmLock(text, source string) []component {
	var out []component
	inPackages := false
	for _, raw := range strings.Split(text, "\n") {
		if raw == "" || strings.HasPrefix(strings.TrimSpace(raw), "#") {
			continue
		}
		// A line at column zero ends the block it does not open.
		if raw[0] != ' ' && raw[0] != '\t' {
			inPackages = strings.TrimSpace(raw) == "packages:"
			continue
		}
		if !inPackages {
			continue
		}
		// Only the block's own keys, not the `resolution:` lines under them.
		if indentOf(raw) != 2 {
			continue
		}
		key := strings.TrimSpace(raw)
		if !strings.HasSuffix(key, ":") {
			continue
		}
		if c, ok := pnpmComponent(strings.TrimSuffix(key, ":"), source); ok {
			out = append(out, c)
		}
	}
	return out
}

func pnpmComponent(key, source string) (component, bool) {
	key = strings.Trim(key, `'"`)
	// The peer suffix describes which build of the package this is; the
	// package is what OSV answers about.
	if i := strings.IndexByte(key, '('); i > 0 {
		key = key[:i]
	}
	key = strings.TrimPrefix(key, "/")
	if key == "" {
		return component{}, false
	}
	name, version := "", ""
	if i := strings.LastIndexByte(key, '@'); i > 0 {
		// v6/v9, and the leading @ of a scope is never the separator.
		name, version = key[:i], key[i+1:]
	} else if i := strings.LastIndexByte(key, '/'); i > 0 {
		name, version = key[:i], key[i+1:] // v5
	}
	if name == "" || version == "" || !isVersionish(version) {
		return component{}, false
	}
	return component{ecosystem: "npm", name: name, version: version, source: source}, true
}

// parseYarnLock handles both yarn lockfile dialects with one scanner,
// because structurally they are the same file: a spec line at column zero,
// then an indented `version` for it. Only the punctuation differs —
//
//	v1      "pkg@^7.0.0", "pkg@^7.10.4":     then    version "7.12.11"
//	berry   "pkg@npm:^7.0.0":                then    version: 7.12.11
//
// Berry also lists the workspaces themselves, resolved to `workspace:` — the
// project's own packages, which are not dependencies and which OSV has never
// heard of.
func parseYarnLock(text, source string) []component {
	var out []component
	name := ""
	for _, raw := range strings.Split(text, "\n") {
		trimmed := strings.TrimSpace(raw)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		if raw[0] != ' ' && raw[0] != '\t' {
			name = ""
			if !strings.HasSuffix(trimmed, ":") {
				continue
			}
			// One entry can satisfy several ranges; they all resolve to the
			// same package, so the first spec is enough.
			spec := strings.Trim(strings.TrimSpace(strings.Split(strings.TrimSuffix(trimmed, ":"), ",")[0]), `'"`)
			if spec == "__metadata" {
				continue
			}
			at := strings.LastIndexByte(spec, '@')
			if at <= 0 {
				continue
			}
			if strings.HasPrefix(spec[at+1:], "workspace:") {
				continue // the project's own package, not a dependency
			}
			name = spec[:at]
			continue
		}
		if name == "" || !strings.HasPrefix(trimmed, "version") {
			continue
		}
		version := strings.Trim(strings.TrimSpace(
			strings.TrimPrefix(strings.TrimPrefix(trimmed, "version"), ":")), `'"`)
		if isVersionish(version) {
			out = append(out, component{ecosystem: "npm", name: name, version: version, source: source})
		}
		name = ""
	}
	return out
}

// parseTOMLLock reads the [[package]] tables that uv, Poetry and Cargo all
// happen to use — the same three lines in the same shape, so one scanner
// serves three ecosystems rather than three near-identical ones drifting
// apart.
//
// The project's own packages are excluded. Every one of these formats records
// them: uv marks the root `virtual` or `editable`, Poetry gives a path
// dependency a `directory` source, and a Cargo workspace member is the entry
// with no `source` at all. Left in, they become inventory rows for packages
// that do not exist on any registry, and the count at the top of the report
// stops matching what was actually checked.
func parseTOMLLock(text, source, ecosystem string, localWhenSourceless bool) []component {
	var out []component
	var name, version string
	hasSource, local := false, false
	flush := func() {
		if name != "" && version != "" && !local && !(localWhenSourceless && !hasSource) {
			out = append(out, component{ecosystem: ecosystem, name: name, version: version, source: source})
		}
		name, version, hasSource, local = "", "", false, false
	}
	for _, raw := range strings.Split(text, "\n") {
		line := strings.TrimSpace(raw)
		switch {
		case line == "[[package]]":
			flush()
			continue
		// A [package.source] or [[package.wheels]] subtable belongs to the
		// record above it — that is where Poetry records a path dependency —
		// so it must not close the record. Any other table header does.
		case strings.HasPrefix(line, "[package.") || strings.HasPrefix(line, "[[package."):
			continue
		case strings.HasPrefix(line, "["):
			flush()
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		val = strings.Trim(strings.TrimSpace(val), `"'`)
		switch strings.TrimSpace(key) {
		case "name":
			if name == "" {
				name = val
			}
		case "version":
			if version == "" {
				version = val
			}
		case "source":
			hasSource = true
			if isLocalSource(val) {
				local = true
			}
		case "type", "url", "path", "editable", "virtual", "directory":
			if isLocalSource(line) {
				local = true
			}
		}
	}
	flush()
	return out
}

// isLocalSource recognises the several ways these formats say "this one is
// not from a registry, it is a directory on the machine that built the lock".
func isLocalSource(s string) bool {
	for _, marker := range []string{"editable", "virtual", "directory", "path"} {
		if strings.Contains(s, marker) {
			return true
		}
	}
	return false
}

// bunLock is the text lockfile bun 1.2 introduced. Each entry's first element
// is the canonical "name@version"; the map key is an install path, which for
// a nested duplicate is not the package name.
type bunLock struct {
	Packages map[string][]json.RawMessage `json:"packages"`
}

func parseBunLock(data []byte, source string) ([]component, error) {
	var lock bunLock
	// bun writes JSONC: comments and trailing commas, which encoding/json
	// rejects outright rather than tolerating.
	if err := json.Unmarshal(stripJSONC(data), &lock); err != nil {
		return nil, err
	}
	var out []component
	for _, entry := range lock.Packages {
		if len(entry) == 0 {
			continue
		}
		var spec string
		if err := json.Unmarshal(entry[0], &spec); err != nil {
			continue
		}
		at := strings.LastIndexByte(spec, '@')
		if at <= 0 {
			continue
		}
		name, version := spec[:at], spec[at+1:]
		// "workspace:packages/api" and "npm:foo@1.0.0" are resolutions, not
		// versions; only the first is a package this project publishes.
		if !isVersionish(version) {
			continue
		}
		out = append(out, component{ecosystem: "npm", name: name, version: version, source: source})
	}
	return out, nil
}

// stripJSONC removes what JSONC allows and JSON does not — line comments,
// block comments, and a comma before a closing brace or bracket — without
// touching anything inside a string, where "//" is a URL and not a comment.
func stripJSONC(data []byte) []byte {
	out := make([]byte, 0, len(data))
	inStr, esc := false, false
	for i := 0; i < len(data); i++ {
		c := data[i]
		if inStr {
			out = append(out, c)
			switch {
			case esc:
				esc = false
			case c == '\\':
				esc = true
			case c == '"':
				inStr = false
			}
			continue
		}
		switch {
		case c == '"':
			inStr = true
			out = append(out, c)
		case c == '/' && i+1 < len(data) && data[i+1] == '/':
			for i < len(data) && data[i] != '\n' {
				i++
			}
			out = append(out, '\n')
		case c == '/' && i+1 < len(data) && data[i+1] == '*':
			for i += 2; i+1 < len(data) && !(data[i] == '*' && data[i+1] == '/'); i++ {
			}
			i++
		case c == ',':
			j := i + 1
			for j < len(data) && (data[j] == ' ' || data[j] == '\t' || data[j] == '\n' || data[j] == '\r') {
				j++
			}
			if j < len(data) && (data[j] == '}' || data[j] == ']') {
				continue
			}
			out = append(out, c)
		default:
			out = append(out, c)
		}
	}
	return out
}

// composerLock. Dev dependencies are included: a vulnerable test framework is
// still running on somebody's CI machine with the repository checked out.
type composerLock struct {
	Packages    []composerPkg `json:"packages"`
	PackagesDev []composerPkg `json:"packages-dev"`
}

type composerPkg struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

func parseComposerLock(data []byte, source string) ([]component, error) {
	var lock composerLock
	if err := json.Unmarshal(data, &lock); err != nil {
		return nil, err
	}
	var out []component
	for _, p := range append(append([]composerPkg{}, lock.Packages...), lock.PackagesDev...) {
		// Composer records "v1.2.3"; Packagist advisories in OSV are indexed
		// without the prefix, and a version that does not match returns no
		// vulnerabilities rather than an error.
		version := p.Version
		if len(version) > 1 && version[0] == 'v' && version[1] >= '0' && version[1] <= '9' {
			version = version[1:]
		}
		if p.Name == "" || version == "" {
			continue
		}
		out = append(out, component{ecosystem: "Packagist", name: p.Name, version: version, source: source})
	}
	return out, nil
}

// pipfileLock pins with the same "==" requirements.txt uses.
type pipfileLock struct {
	Default map[string]struct {
		Version string `json:"version"`
	} `json:"default"`
	Develop map[string]struct {
		Version string `json:"version"`
	} `json:"develop"`
}

func parsePipfileLock(data []byte, source string) ([]component, error) {
	var lock pipfileLock
	if err := json.Unmarshal(data, &lock); err != nil {
		return nil, err
	}
	var out []component
	for _, group := range []map[string]struct {
		Version string `json:"version"`
	}{lock.Default, lock.Develop} {
		for name, pkg := range group {
			version := strings.TrimPrefix(strings.TrimSpace(pkg.Version), "==")
			if name == "" || version == "" {
				continue
			}
			out = append(out, component{ecosystem: "PyPI", name: name, version: version, source: source})
		}
	}
	return out, nil
}

// parseGemfileLock reads the GEM specs block. Indentation is the grammar
// here: four spaces is a gem, six is one of that gem's requirements, and a
// requirement carries a range rather than the resolved version.
func parseGemfileLock(text, source string) []component {
	var out []component
	inSpecs := false
	for _, raw := range strings.Split(text, "\n") {
		trimmed := strings.TrimSpace(raw)
		if trimmed == "" {
			continue
		}
		if indentOf(raw) <= 2 {
			inSpecs = trimmed == "specs:"
			continue
		}
		if !inSpecs || indentOf(raw) != 4 {
			continue
		}
		name, rest, ok := strings.Cut(trimmed, " (")
		if !ok {
			continue
		}
		version := strings.TrimSuffix(strings.TrimSpace(rest), ")")
		if name == "" || !isVersionish(version) {
			continue
		}
		out = append(out, component{ecosystem: "RubyGems", name: name, version: version, source: source})
	}
	return out
}

// isVersionish rejects the things these formats put where a version goes when
// the answer is not a version — "workspace:packages/api", "npm:lodash@4",
// "link:../shared", ">= 4.2". Sending one to OSV is not an error there; it is
// an empty answer, which reads exactly like "not vulnerable".
func isVersionish(v string) bool {
	if v == "" || strings.ContainsAny(v, ":<>= ") {
		return false
	}
	return v[0] >= '0' && v[0] <= '9'
}

func indentOf(line string) int {
	for i := 0; i < len(line); i++ {
		if line[i] != ' ' {
			return i
		}
	}
	return len(line)
}
