package net

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/this-is-tobi/rule-them-all/pkg/plugin"
	"github.com/this-is-tobi/rule-them-all/pkg/view"
)

// resolvFixture points the plugin at a scratch resolv.conf.
func resolvFixture(t *testing.T, content string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Setenv("RTA_DATA_DIR", t.TempDir())
	orig := resolvConf
	resolvConf = path
	t.Cleanup(func() { resolvConf = orig })
	return path
}

func pairs(t *testing.T, v view.View) map[string]string {
	t.Helper()
	kv, ok := v.(view.KeyValue)
	if !ok {
		t.Fatalf("want KeyValue, got %s", view.TypeOf(v))
	}
	out := map[string]string{}
	for _, p := range kv.Pairs {
		out[p.Key] = p.Value
	}
	return out
}

func TestResolverListReportsServersAndOwnership(t *testing.T) {
	resolvFixture(t, "# a note\nsearch corp.example.com lan\nnameserver 192.168.1.1\nnameserver 9.9.9.9\noptions ndots:2\n")
	got := pairs(t, run(t, runResolverList, nil))

	if got["nameserver"] != "192.168.1.1" {
		t.Errorf("primary = %q", got["nameserver"])
	}
	// The order is the failover order, and shown as such.
	if got["fallback 1"] != "9.9.9.9" {
		t.Errorf("fallback = %q", got["fallback 1"])
	}
	if got["search"] != "corp.example.com lan" {
		t.Errorf("search = %q", got["search"])
	}
	if got["options"] != "ndots:2" {
		t.Errorf("options = %q", got["options"])
	}
	if !strings.Contains(got["managed by"], "safe to edit") {
		t.Errorf("ownership = %q", got["managed by"])
	}
}

// The most useful thing this can tell you is that editing the file is
// pointless, so it has to lead with that.
func TestResolverListNamesTheOwnerOfAGeneratedFile(t *testing.T) {
	resolvFixture(t, "# Generated by NetworkManager\nnameserver 1.1.1.1\n")
	if got := pairs(t, run(t, runResolverList, nil))["managed by"]; !strings.Contains(got, "NetworkManager") {
		t.Errorf("ownership = %q", got)
	}
}

func TestResolverListEmptyIsExplicit(t *testing.T) {
	resolvFixture(t, "# nothing configured\n")
	if got := pairs(t, run(t, runResolverList, nil))["nameservers"]; got != "none configured" {
		t.Errorf("empty resolv.conf = %q", got)
	}
}

// Setting the nameservers replaces those lines and nothing else: search
// domains and options are separate settings that a resolver change should
// not quietly drop.
func TestResolverSetKeepsSearchAndOptions(t *testing.T) {
	path := resolvFixture(t, "# my notes\nsearch corp.example.com\nnameserver 192.168.1.1\noptions ndots:2\n")
	run(t, runResolverSet, map[string]any{"server": []string{"1.1.1.1", "9.9.9.9"}})

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	got := string(data)
	for _, keep := range []string{"# my notes", "search corp.example.com", "options ndots:2"} {
		if !strings.Contains(got, keep) {
			t.Errorf("lost %q:\n%s", keep, got)
		}
	}
	if !strings.Contains(got, "nameserver 1.1.1.1\nnameserver 9.9.9.9") {
		t.Errorf("new nameservers missing or out of order:\n%s", got)
	}
	if strings.Contains(got, "192.168.1.1") {
		t.Errorf("old nameserver survived:\n%s", got)
	}
}

func TestResolverSetOnAFileWithNoNameservers(t *testing.T) {
	path := resolvFixture(t, "search corp.example.com\n")
	run(t, runResolverSet, map[string]any{"server": []string{"1.1.1.1"}})

	data, _ := os.ReadFile(path)
	if !strings.Contains(string(data), "nameserver 1.1.1.1") {
		t.Errorf("nameserver not added:\n%s", data)
	}
}

// Writing a generated file is worse than refusing: the change works, then
// vanishes at the next reboot with nothing pointing at why.
func TestResolverSetRefusesAManagedFile(t *testing.T) {
	path := resolvFixture(t, "# Generated by systemd-resolved. DO NOT EDIT.\nnameserver 127.0.0.53\n")
	_, err := runResolverSet(context.Background(),
		plugin.NewRequest(map[string]any{"server": []string{"1.1.1.1"}}, false, true))
	ve := view.AsError(err, "x")
	if ve.Code != "net.sysfile.managed" || ve.Hint == "" {
		t.Fatalf("want net.sysfile.managed with hint, got %+v", ve)
	}
	if data, _ := os.ReadFile(path); strings.Contains(string(data), "1.1.1.1") {
		t.Error("the refusal still wrote the file")
	}
}

// A symlink is how systemd-resolved and friends actually present the file,
// and replacing it with a regular file would break the whole arrangement.
func TestResolverSetRefusesASymlink(t *testing.T) {
	dir := t.TempDir()
	real := filepath.Join(dir, "stub-resolv.conf")
	if err := os.WriteFile(real, []byte("nameserver 127.0.0.53\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	link := filepath.Join(dir, "resolv.conf")
	if err := os.Symlink(real, link); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	t.Setenv("RTA_DATA_DIR", t.TempDir())
	orig := resolvConf
	resolvConf = link
	t.Cleanup(func() { resolvConf = orig })

	_, err := runResolverSet(context.Background(),
		plugin.NewRequest(map[string]any{"server": []string{"1.1.1.1"}}, false, true))
	ve := view.AsError(err, "x")
	if ve.Code != "net.sysfile.managed" || !strings.Contains(ve.Message, "symlink") {
		t.Fatalf("want a symlink refusal, got %+v", ve)
	}
}

// --force writes anyway, and says the change is going to be undone.
func TestResolverSetForceWarnsItWillBeOverwritten(t *testing.T) {
	path := resolvFixture(t, "# Generated by NetworkManager\nnameserver 192.168.1.1\n")
	body := run(t, runResolverSet, map[string]any{
		"server": []string{"1.1.1.1"}, "force": true,
	}).(view.Text).Body

	if !strings.Contains(body, "warning") || !strings.Contains(body, "NetworkManager") {
		t.Errorf("forced write should repeat the warning: %q", body)
	}
	if data, _ := os.ReadFile(path); !strings.Contains(string(data), "1.1.1.1") {
		t.Errorf("--force did not write:\n%s", data)
	}
}

func TestResolverSetBadServerIsCoded(t *testing.T) {
	resolvFixture(t, "nameserver 1.1.1.1\n")
	_, err := runResolverSet(context.Background(),
		plugin.NewRequest(map[string]any{"server": []string{"dns.example.com"}}, false, true))
	ve := view.AsError(err, "x")
	if ve.Code != "net.resolver.badserver" || ve.Hint == "" {
		t.Errorf("want net.resolver.badserver with hint, got %+v", ve)
	}
}

func TestResolverSetDryRunChangesNothing(t *testing.T) {
	path := resolvFixture(t, "nameserver 192.168.1.1\n")
	v, err := runResolverSet(context.Background(),
		plugin.NewRequest(map[string]any{"server": []string{"1.1.1.1"}}, true, true))
	if err != nil {
		t.Fatal(err)
	}
	if body := v.(view.Text).Body; !strings.HasPrefix(body, "would ") {
		t.Errorf("dry-run = %q", body)
	}
	if data, _ := os.ReadFile(path); !strings.Contains(string(data), "192.168.1.1") {
		t.Error("a dry run modified the file")
	}
}

func TestResolverSetBacksUpFirst(t *testing.T) {
	resolvFixture(t, "nameserver 192.168.1.1\n")
	body := run(t, runResolverSet, map[string]any{"server": []string{"1.1.1.1"}}).(view.Text).Body
	if !strings.Contains(body, "saved to") {
		t.Fatalf("no backup reported: %q", body)
	}
	entries, err := os.ReadDir(backupDir())
	if err != nil || len(entries) != 1 {
		t.Fatalf("backups = %v (%v)", entries, err)
	}
}

// --- Safety classes ---------------------------------------------------------

// Editing name resolution for every process on the machine is not an
// ordinary write: a wrong entry reroutes traffic instead of failing, so an
// agent needs a per-capability allowlist rather than blanket --allow-write.
func TestSystemFileEditsAreDestructive(t *testing.T) {
	want := map[string]plugin.Safety{
		"net.hosts.list":    plugin.Read,
		"net.hosts.add":     plugin.Destructive,
		"net.hosts.rm":      plugin.Destructive,
		"net.hosts.toggle":  plugin.Destructive,
		"net.resolver.list": plugin.Read,
		"net.resolver.set":  plugin.Destructive,
	}
	seen := map[string]bool{}
	for _, c := range Plugin().Capabilities {
		if w, ok := want[c.ID]; ok {
			seen[c.ID] = true
			if c.Safety != w {
				t.Errorf("%s safety = %s, want %s", c.ID, c.Safety, w)
			}
		}
	}
	for id := range want {
		if !seen[id] {
			t.Errorf("capability %s missing", id)
		}
	}
}
