package net

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/this-is-tobi/rta/builtin/internal/itemstore"
	"github.com/this-is-tobi/rta/builtin/internal/pathin"
	"github.com/this-is-tobi/rta/internal/atomicfile"
	"github.com/this-is-tobi/rta/pkg/plugin"
	"github.com/this-is-tobi/rta/pkg/view"
)

// Editing root-owned network configuration.
//
// /etc/hosts and /etc/resolv.conf decide where every process on the machine
// sends its traffic. Getting them wrong does not produce an error — it
// produces a machine that quietly talks to the wrong server, which is the
// worst kind of failure to debug. So the rules here are strict:
//
//   - Everything not being changed survives byte for byte. Comments,
//     ordering and spacing in a hosts file are somebody's notes to
//     themselves; a tool that reformats them on the way past is a tool
//     people stop using.
//   - Every write is preceded by a backup and performed atomically, so an
//     interrupted write cannot leave the machine with half a resolver.
//   - A file the system generates is not ours to edit. Writing to one is
//     worse than refusing: the change appears to work and then vanishes at
//     the next reboot, DHCP lease, or network change.

// backupDir keeps copies out of /etc — a directory full of hosts.bak.3 is
// its own kind of mess, and these belong with rta's own state.
func backupDir() string { return filepath.Join(itemstore.DataDir(), "backups") }

// maxHostsBytes and maxResolvBytes are more than either file ever holds,
// with room to spare: the largest hosts files in use are ad-blocking lists of
// a few megabytes, and a resolv.conf is under a kilobyte, since the resolver
// reads three nameservers and a search list of 256 characters. A file past
// the cap is not the file the input names, and reading it whole was the
// server's memory spent on the caller's say-so (pathin).
const (
	maxHostsBytes  = 32 << 20
	maxResolvBytes = 1 << 20
)

// readLines reads a configuration file as lines, keeping them exactly as
// written. sf is the surface asking, for pathin's line on what a path may
// name, and max the file's cap.
func readLines(sf plugin.Surface, path string, max int) ([]string, *view.Error) {
	data, err := pathin.Read(sf, path, max)
	if err != nil {
		return nil, unreadable(path, err)
	}
	text := strings.TrimSuffix(string(data), "\n")
	if text == "" {
		return nil, nil
	}
	return strings.Split(text, "\n"), nil
}

// managedBy reports what generates this file and what to do about it, or
// zero values when nothing does.
//
// A symlink is the giveaway on modern Linux (systemd-resolved, resolvconf
// and NetworkManager all point /etc/resolv.conf somewhere under /run) and on
// macOS; generators that write a real file announce themselves in a header.
// The advice comes back with the diagnosis because the two differ: a symlink
// has a real file at the other end you could edit, a header does not. force
// is the override as the caller gives it (plugin.Surface.InputName), which
// the advice names.
//
// sf is the surface asking, for the file pathin opens to read the header.
func managedBy(sf plugin.Surface, path, force string) (what, advice string) {
	if target, err := os.Readlink(path); err == nil {
		return "a symlink to " + target,
			"edit " + target + " instead, or configure whatever writes it — " + force + " would " +
				"replace the symlink with a regular file, which usually breaks more than it fixes"
	}
	f, _, err := pathin.Open(sf, path)
	if err != nil {
		return "", ""
	}
	defer func() { _ = f.Close() }()
	head := make([]byte, 512)
	n, _ := io.ReadFull(f, head)
	lower := strings.ToLower(string(head[:n]))
	for _, m := range []struct{ marker, owner string }{
		{"systemd-resolved", "systemd-resolved"},
		{"networkmanager", "NetworkManager"},
		{"resolvconf", "resolvconf"},
		{"generated by", ""},
		{"do not edit", ""},
	} {
		if !strings.Contains(lower, m.marker) {
			continue
		}
		if m.owner == "" {
			return "another program", "configure that program instead, or give " + force + " if you are sure"
		}
		return m.owner, "configure " + m.owner + " instead, or give " + force + " if you are sure"
	}
	return "", ""
}

// backup copies path into rta's own state directory before it is changed,
// and returns where it went so the message can say. sf is the surface asking,
// for the file pathin opens.
//
// Every backup gets its own file. Two edits in the same second are ordinary
// — `hosts add` then `hosts toggle` takes about that long — and a timestamp
// alone would have the second silently overwrite the first, leaving "saved
// to X" pointing at a copy of the very state it claimed to preserve.
func backup(sf plugin.Surface, path string) (string, *view.Error) {
	src, _, err := pathin.Open(sf, path)
	if err != nil {
		return "", unreadable(path, err)
	}
	defer func() { _ = src.Close() }()
	dir := backupDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", view.Errorf("net.sysfile.backup", "creating %s: %v", dir, err)
	}
	base := filepath.Join(dir, fmt.Sprintf("%s.%s", filepath.Base(path), time.Now().Format("20060102-150405")))
	for i := 0; ; i++ {
		dest := base
		if i > 0 {
			dest = fmt.Sprintf("%s-%d", base, i)
		}
		// O_EXCL: the check and the claim have to be one step, or two edits
		// racing land on the same name anyway.
		f, err := os.OpenFile(dest, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
		if os.IsExist(err) {
			continue
		}
		if err != nil {
			return "", view.Errorf("net.sysfile.backup", "writing %s: %v", dest, err)
		}
		_, werr := io.Copy(f, src)
		cerr := f.Close()
		if werr != nil || cerr != nil {
			return "", view.Errorf("net.sysfile.backup", "writing %s: %v", dest, firstErr(werr, cerr))
		}
		return dest, nil
	}
}

// unreadable is the refusal of a file readLines or backup could not read,
// saying which of pathin's refusals it met when it was one of them.
func unreadable(path string, err error) *view.Error {
	var notAFile *pathin.NotAFileError
	var tooLarge *pathin.TooLargeError
	switch {
	case errors.As(err, &notAFile):
		return view.Errorf("net.sysfile.notafile", "%v", err).
			WithHint("name the file itself — a hosts file or a resolv.conf is a regular file")
	case errors.As(err, &tooLarge):
		return view.Errorf("net.sysfile.toolarge", "%v, more than a hosts file or a resolv.conf holds", err).
			WithHint("name the hosts file or the resolv.conf itself")
	}
	return view.Errorf("net.sysfile.unreadable", "reading %s: %v", path, err)
}

func firstErr(a, b error) error {
	if a != nil {
		return a
	}
	return b
}

// writeLines replaces a configuration file atomically, keeping its mode.
// Atomically because a torn /etc/hosts is a machine that cannot resolve its
// own name; see internal/atomicfile for how. sf is the surface asking, for
// the way a refusal to write says root is reached.
func writeLines(sf plugin.Surface, path string, lines []string) *view.Error {
	info, err := os.Stat(path)
	if err != nil {
		return view.Errorf("net.sysfile.unreadable", "reading %s: %v", path, err)
	}
	body := strings.Join(lines, "\n") + "\n"

	// Keep the original permissions rather than the 0600 a fresh file would
	// get: a 0600 /etc/hosts breaks name resolution for every non-root
	// process, which is a worse outage than the edit was a fix.
	if err := atomicfile.Write(path, []byte(body), info.Mode().Perm()); err != nil {
		return permissionError(sf, path, err)
	}
	return nil
}

// permissionError turns "permission denied" into the sentence that actually
// helps, since needing root here is the expected case and not a mistake.
//
// errors.Is rather than os.IsPermission: the write goes through atomicfile,
// which wraps, and os.IsPermission only unwraps the handful of error types
// the os package defines itself. It looked equivalent and would have quietly
// dropped the one hint the caller needs, on the one path they always take.
//
// Only a command line is run again with sudo. A TUI and an MCP server run as
// whoever started them, and "the same command" told an agent to rerun one it
// never typed: from either, the change is made at a terminal, and over MCP by
// the operator.
func permissionError(sf plugin.Surface, path string, err error) *view.Error {
	if errors.Is(err, fs.ErrPermission) {
		hint := "run the same command with sudo — editing " + path + " needs root"
		switch sf {
		case plugin.SurfaceMCP:
			hint = "editing " + path + " needs root, which this server does not run as — the change is " +
				"the operator's to make, with sudo at a terminal"
		case plugin.SurfaceTUI:
			hint = "editing " + path + " needs root, which the TUI does not run as — make the change at a " +
				"terminal with sudo"
		}
		return view.Errorf("net.sysfile.permission", "cannot write %s: permission denied", path).WithHint(hint)
	}
	return view.Errorf("net.sysfile.write", "writing %s: %v", path, err)
}

// guardManaged refuses to edit a file something else generates, unless the
// caller says they know. Silently editing a generated file is worse than
// refusing: the change works, then disappears at the next reboot or lease
// renewal, and nothing points at why.
func guardManaged(sf plugin.Surface, path string, force bool) *view.Error {
	what, advice := managedBy(sf, path, sf.InputName("force"))
	if what == "" || force {
		return nil
	}
	return view.Errorf("net.sysfile.managed", "%s is %s, so changes here get overwritten", path, what).
		WithHint(advice)
}
