package net

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/this-is-tobi/rule-them-all/builtin/internal/itemstore"
	"github.com/this-is-tobi/rule-them-all/pkg/view"
)

// Editing root-owned network configuration.
//
// /etc/hosts and /etc/resolv.conf decide where every process on the machine
// sends its traffic. Getting them wrong does not produce an error — it
// produces a machine that quietly talks to the wrong server, which is the
// worst kind of failure to debug. So the rules here are strict:
//
//   - Everything not being changed survives byte for byte. Comments,
//     ordering and spacing in a hosts file are somebody's notes to
//     themselves; a tool that reformats them on the way past is a tool
//     people stop using.
//   - Every write is preceded by a backup and performed atomically, so an
//     interrupted write cannot leave the machine with half a resolver.
//   - A file the system generates is not ours to edit. Writing to one is
//     worse than refusing: the change appears to work and then vanishes at
//     the next reboot, DHCP lease, or network change.

// backupDir keeps copies out of /etc — a directory full of hosts.bak.3 is
// its own kind of mess, and these belong with rta's own state.
func backupDir() string { return filepath.Join(itemstore.DataDir(), "backups") }

// readLines reads a configuration file as lines, keeping them exactly as
// written.
func readLines(path string) ([]string, *view.Error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, view.Errorf("net.sysfile.unreadable", "reading %s: %v", path, err)
	}
	text := strings.TrimSuffix(string(data), "\n")
	if text == "" {
		return nil, nil
	}
	return strings.Split(text, "\n"), nil
}

// managedBy reports what generates this file and what to do about it, or
// zero values when nothing does.
//
// A symlink is the giveaway on modern Linux (systemd-resolved, resolvconf
// and NetworkManager all point /etc/resolv.conf somewhere under /run) and on
// macOS; generators that write a real file announce themselves in a header.
// The advice comes back with the diagnosis because the two differ: a symlink
// has a real file at the other end you could edit, a header does not.
func managedBy(path string) (what, advice string) {
	if target, err := os.Readlink(path); err == nil {
		return "a symlink to " + target,
			"edit " + target + " instead, or configure whatever writes it — --force would " +
				"replace the symlink with a regular file, which usually breaks more than it fixes"
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", ""
	}
	head := string(data)
	if len(head) > 512 {
		head = head[:512]
	}
	lower := strings.ToLower(head)
	for _, m := range []struct{ marker, owner string }{
		{"systemd-resolved", "systemd-resolved"},
		{"networkmanager", "NetworkManager"},
		{"resolvconf", "resolvconf"},
		{"generated by", ""},
		{"do not edit", ""},
	} {
		if !strings.Contains(lower, m.marker) {
			continue
		}
		if m.owner == "" {
			return "another program", "configure that program instead, or pass --force if you are sure"
		}
		return m.owner, "configure " + m.owner + " instead, or pass --force if you are sure"
	}
	return "", ""
}

// backup copies path into rta's own state directory before it is changed,
// and returns where it went so the message can say.
//
// Every backup gets its own file. Two edits in the same second are ordinary
// — `hosts add` then `hosts toggle` takes about that long — and a timestamp
// alone would have the second silently overwrite the first, leaving "saved
// to X" pointing at a copy of the very state it claimed to preserve.
func backup(path string) (string, *view.Error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", view.Errorf("net.sysfile.unreadable", "reading %s: %v", path, err)
	}
	dir := backupDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", view.Errorf("net.sysfile.backup", "creating %s: %v", dir, err)
	}
	base := filepath.Join(dir, fmt.Sprintf("%s.%s", filepath.Base(path), time.Now().Format("20060102-150405")))
	for i := 0; ; i++ {
		dest := base
		if i > 0 {
			dest = fmt.Sprintf("%s-%d", base, i)
		}
		// O_EXCL: the check and the claim have to be one step, or two edits
		// racing land on the same name anyway.
		f, err := os.OpenFile(dest, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
		if os.IsExist(err) {
			continue
		}
		if err != nil {
			return "", view.Errorf("net.sysfile.backup", "writing %s: %v", dest, err)
		}
		_, werr := f.Write(data)
		cerr := f.Close()
		if werr != nil || cerr != nil {
			return "", view.Errorf("net.sysfile.backup", "writing %s: %v", dest, firstErr(werr, cerr))
		}
		return dest, nil
	}
}

func firstErr(a, b error) error {
	if a != nil {
		return a
	}
	return b
}

// writeLines replaces a configuration file atomically, keeping its mode.
//
// The temporary file is created beside the target so the rename stays within
// one filesystem — a copy across /tmp would not be atomic, and a torn
// /etc/hosts is a machine that cannot resolve its own name.
func writeLines(path string, lines []string) *view.Error {
	info, err := os.Stat(path)
	if err != nil {
		return view.Errorf("net.sysfile.unreadable", "reading %s: %v", path, err)
	}
	body := strings.Join(lines, "\n") + "\n"

	tmp, err := os.CreateTemp(filepath.Dir(path), "."+filepath.Base(path)+"-rta-*")
	if err != nil {
		return permissionError(path, err)
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write([]byte(body)); err != nil {
		tmp.Close()
		return view.Errorf("net.sysfile.write", "writing %s: %v", path, err)
	}
	if err := tmp.Close(); err != nil {
		return view.Errorf("net.sysfile.write", "closing %s: %v", path, err)
	}
	// Keep the original permissions: CreateTemp makes a 0600 file, and a
	// 0600 /etc/hosts breaks name resolution for every non-root process.
	if err := os.Chmod(tmp.Name(), info.Mode().Perm()); err != nil {
		return view.Errorf("net.sysfile.write", "setting permissions on %s: %v", path, err)
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return permissionError(path, err)
	}
	return nil
}

// permissionError turns "permission denied" into the sentence that actually
// helps, since needing root here is the expected case and not a mistake.
func permissionError(path string, err error) *view.Error {
	if os.IsPermission(err) {
		return view.Errorf("net.sysfile.permission", "cannot write %s: permission denied", path).
			WithHint("run the same command with sudo — editing " + path + " needs root")
	}
	return view.Errorf("net.sysfile.write", "writing %s: %v", path, err)
}

// guardManaged refuses to edit a file something else generates, unless the
// caller says they know. Silently editing a generated file is worse than
// refusing: the change works, then disappears at the next reboot or lease
// renewal, and nothing points at why.
func guardManaged(path string, force bool) *view.Error {
	what, advice := managedBy(path)
	if what == "" || force {
		return nil
	}
	return view.Errorf("net.sysfile.managed", "%s is %s, so changes here get overwritten", path, what).
		WithHint(advice)
}
